### ISSUE TITLE
Python Code

### ISSUE THREAD

**Issue by jbeth1** [jbeth1/3D_Membrane_Model#1]
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from scipy.special import jn, jn_zeros
import seaborn as sns

# Constants
R = 2
a = 1
b = 0

# Range of r and theta values
r_vals = np.linspace(0, R, 100)
theta_vals = np.linspace(0, 2*np.pi, 100)

# Creates a meshgrid of r and theta values
r, theta = np.meshgrid(r_vals, theta_vals)

# Initializes the figure and subplots
fig = plt.figure(figsize=(12, 10))
ax1 = fig.add_subplot(231, projection='3d') # looked up values to do fig.add_subplot
ax2 = fig.add_subplot(232, projection='3d')
ax3 = fig.add_subplot(233, projection='3d')
ax4 = fig.add_subplot(234, projection='3d')
ax5 = fig.add_subplot(235, projection='3d')
ax6 = fig.add_subplot(236, projection='3d')

# Defines the low-order vibrational modes
modes = [(0, 1), (0, 2), (0, 3), (1, 1), (1, 2), (1, 3)]

# Loops through the modes and plot each one
for i, (n, m) in enumerate(modes): # goes through i element in (n,m) coordinates

    # Color of the plot 
    sns.color_palette("YlOrBr_r")
    
    # Calculates the alpha value
    alpha = jn_zeros(n, m)[-1]
    
    # Calculates the z value for each (r, theta) point
    z = jn(n, alpha*r/R) * (a*np.cos(n*theta) + b*np.sin(n*theta))
    
    # Plots the surface
    if i == 0:
        ax1.plot_surface(r*np.cos(theta), r*np.sin(theta), z, cmap = "YlOrBr_r")
    elif i == 1:
        ax2.plot_surface(r*np.cos(theta), r*np.sin(theta), z, cmap="YlOrBr_r")
    elif i == 2:
        ax3.plot_surface(r*np.cos(theta), r*np.sin(theta), z, cmap="YlOrBr_r")
    elif i == 3:
        ax4.plot_surface(r*np.cos(theta), r*np.sin(theta), z, cmap="YlOrBr_r")
    elif i == 4:
        ax5.plot_surface(r*np.cos(theta), r*np.sin(theta), z, cmap="YlOrBr_r")
    else:
        ax6.plot_surface(r*np.cos(theta), r*np.sin(theta), z, cmap="YlOrBr_r")

# Axis labels and titles

ax1.set_xlabel('x')
ax1.set_ylabel('y')
ax1.set_zlabel('z')
ax1.set_title('Mode (0, 1)')
ax2.set_xlabel('x')
ax2.set_ylabel('y')
ax2.set_zlabel('z')
ax2.set_title('Mode (0, 2)')
ax3.set_xlabel('x')
ax3.set_ylabel('y')
ax3.set_zlabel('z')
ax3.set_title('Mode (0, 3)')
ax4.set_xlabel('x')
ax4.set_ylabel('y')
ax4.set_zlabel('z')
ax4.set_title('Mode (1, 1)')
ax5.set_xlabel('x')
ax5.set_ylabel('y')
ax5.set_zlabel('z')
ax5.set_title('Mode (1,2)')
ax6.set_xlabel('x')
ax6.set_ylabel('y')
ax6.set_title('Mode (1,3)')

**Comment by jbeth1** [comment]
Run this code to see different vibrational movements of the membrane (can be edited by changing values in the modes and elif statements)

**Comment by RinRyuu** [comment]
can i know what u want to me to do on this
sir?
